[
   {
      "author_association" : "NONE",
      "body" : "> `AssertionError: [node 0] Node returned unexpected exit code (3) vs (0) when stopping`\r\n\r\nHello, I think a clue to solve this issue is to find out where the `exit code (3)` is returned? But I didn't find where the `exit code (3)` is returned in the source code.\r\nWhat do you think?",
      "created_at" : "2023-07-23T11:36:40Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/28115#issuecomment-1646817279",
      "id" : 1646817279,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28115",
      "node_id" : "IC_kwDOABII585iKG__",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1646817279/reactions"
      },
      "updated_at" : "2023-07-23T11:36:40Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1646817279",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/46400566?v=4",
         "events_url" : "https://api.github.com/users/eval-exec/events{/privacy}",
         "followers_url" : "https://api.github.com/users/eval-exec/followers",
         "following_url" : "https://api.github.com/users/eval-exec/following{/other_user}",
         "gists_url" : "https://api.github.com/users/eval-exec/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/eval-exec",
         "id" : 46400566,
         "login" : "eval-exec",
         "node_id" : "MDQ6VXNlcjQ2NDAwNTY2",
         "organizations_url" : "https://api.github.com/users/eval-exec/orgs",
         "received_events_url" : "https://api.github.com/users/eval-exec/received_events",
         "repos_url" : "https://api.github.com/users/eval-exec/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/eval-exec/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/eval-exec/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/eval-exec"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> > `AssertionError: [node 0] Node returned unexpected exit code (3) vs (0) when stopping`\r\n> \r\n> Hello, I think a clue to solve this issue is to find out where the `exit code (3)` is returned? But I didn't find where the `exit code (3)` is returned in the source code. What do you think?\r\n\r\nFrom Microsoft [docs](https://learn.microsoft.com/en-us/previous-versions/k089yyh0(v=vs.140)):\r\n> If the Windows error reporting handler is not invoked, then [`abort`](https://learn.microsoft.com/en-us/previous-versions/k089yyh0(v=vs.140)) calls [`_exit`](https://learn.microsoft.com/en-us/previous-versions/6wdz5232(v=vs.140)) to terminate the process with exit code 3 and returns control to the parent process or the operating system.",
      "created_at" : "2023-09-25T12:31:57Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/28115#issuecomment-1733619543",
      "id" : 1733619543,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28115",
      "node_id" : "IC_kwDOABII585nVO9X",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1733619543/reactions"
      },
      "updated_at" : "2023-09-25T12:31:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1733619543",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/32963518?v=4",
         "events_url" : "https://api.github.com/users/hebasto/events{/privacy}",
         "followers_url" : "https://api.github.com/users/hebasto/followers",
         "following_url" : "https://api.github.com/users/hebasto/following{/other_user}",
         "gists_url" : "https://api.github.com/users/hebasto/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/hebasto",
         "id" : 32963518,
         "login" : "hebasto",
         "node_id" : "MDQ6VXNlcjMyOTYzNTE4",
         "organizations_url" : "https://api.github.com/users/hebasto/orgs",
         "received_events_url" : "https://api.github.com/users/hebasto/received_events",
         "repos_url" : "https://api.github.com/users/hebasto/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/hebasto/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/hebasto/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/hebasto"
      }
   }
]
