{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "Aiming to fix #25652.\r\n\r\nThe failure arises because the test expects `init_wallet()` (the test framework function) to create a wallet with no keys. However, the function also imports the deterministic private key used to receive the coinbase coins.\r\n\r\nThis causes a race within the \"restore using dumped wallet\" case, where we intend to have a new wallet (with no existing keys) to test the 'importwallet()' RPC result.\r\nThe reason why this failure is intermittent is that it depends on other peers delivering the chain right after node2 startup and prior to the test 'node2.getbalance()' call and also the synchronization of the validation queue.",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28325/comments",
   "created_at" : "2023-08-22T15:17:21Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28325/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/28325",
   "id" : 1861686591,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28325/labels{/name}",
   "locked" : false,
   "milestone" : {
      "closed_at" : null,
      "closed_issues" : 28,
      "created_at" : "2023-04-15T11:36:05Z",
      "creator" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      },
      "description" : "",
      "due_on" : null,
      "html_url" : "https://github.com/bitcoin/bitcoin/milestone/60",
      "id" : 9286970,
      "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/milestones/60/labels",
      "node_id" : "MI_kwDOABII584AjbU6",
      "number" : 60,
      "open_issues" : 10,
      "state" : "open",
      "title" : "26.0",
      "updated_at" : "2023-08-23T13:27:52Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/milestones/60"
   },
   "node_id" : "PR_kwDOABII585YgsGf",
   "number" : 28325,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/28325.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28325",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/28325.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28325"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28325/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28325/timeline",
   "title" : "test: wallet_backup.py, fix intermittent failure in \"restore using dumped wallet\"",
   "updated_at" : "2023-08-23T12:51:17Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28325",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
      "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
      "followers_url" : "https://api.github.com/users/furszy/followers",
      "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
      "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/furszy",
      "id" : 5377650,
      "login" : "furszy",
      "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
      "organizations_url" : "https://api.github.com/users/furszy/orgs",
      "received_events_url" : "https://api.github.com/users/furszy/received_events",
      "repos_url" : "https://api.github.com/users/furszy/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/furszy"
   }
}
