[
   {
      "author_association" : "MEMBER",
      "body" : "IIRC someone else had an issue like this and the problem was that their shell was eating the `'`. Can you check that that isn't what's happening?\r\n\r\nCan you also try with the latest master branch? There have been a few fixes for descriptors since 25.0 was released, so this may already be fixed.",
      "created_at" : "2023-08-27T15:27:16Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/28351#issuecomment-1694695865",
      "id" : 1694695865,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28351",
      "node_id" : "IC_kwDOABII585lAwG5",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1694695865/reactions"
      },
      "updated_at" : "2023-08-27T15:27:16Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1694695865",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/3782274?v=4",
         "events_url" : "https://api.github.com/users/achow101/events{/privacy}",
         "followers_url" : "https://api.github.com/users/achow101/followers",
         "following_url" : "https://api.github.com/users/achow101/following{/other_user}",
         "gists_url" : "https://api.github.com/users/achow101/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/achow101",
         "id" : 3782274,
         "login" : "achow101",
         "node_id" : "MDQ6VXNlcjM3ODIyNzQ=",
         "organizations_url" : "https://api.github.com/users/achow101/orgs",
         "received_events_url" : "https://api.github.com/users/achow101/received_events",
         "repos_url" : "https://api.github.com/users/achow101/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/achow101/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/achow101/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/achow101"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I just tried with a direct RPC call using this [script](https://github.com/pythcoiner/BitcoinRpcClient/blob/30dd854a26ae4db89b860fbb2c23497db41571d0/main.py), everything goes well.\r\n\r\n> IIRC someone else had an issue like this and the problem was that their shell was eating the `'`. Can you check that that isn't what's happening?\r\n> \r\nany idea how to check this? using another shell?\r\n\r\n> Can you also try with the latest master branch? There have been a few fixes for descriptors since 25.0 was released, so this may already be fixed.\r\n\r\nwill build from the last master\r\n",
      "created_at" : "2023-08-27T15:34:03Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/28351#issuecomment-1694697402",
      "id" : 1694697402,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28351",
      "node_id" : "IC_kwDOABII585lAwe6",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1694697402/reactions"
      },
      "updated_at" : "2023-08-27T15:36:30Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1694697402",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/124568858?v=4",
         "events_url" : "https://api.github.com/users/pythcoiner/events{/privacy}",
         "followers_url" : "https://api.github.com/users/pythcoiner/followers",
         "following_url" : "https://api.github.com/users/pythcoiner/following{/other_user}",
         "gists_url" : "https://api.github.com/users/pythcoiner/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/pythcoiner",
         "id" : 124568858,
         "login" : "pythcoiner",
         "node_id" : "U_kgDOB2zFGg",
         "organizations_url" : "https://api.github.com/users/pythcoiner/orgs",
         "received_events_url" : "https://api.github.com/users/pythcoiner/received_events",
         "repos_url" : "https://api.github.com/users/pythcoiner/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/pythcoiner/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/pythcoiner/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/pythcoiner"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> I just tried with a direct RPC call using this [script](https://github.com/pythcoiner/BitcoinRpcClient/blob/30dd854a26ae4db89b860fbb2c23497db41571d0/main.py), everything goes well.\r\n\r\nTo clarify, the script uses the checksum returned by `getdescriptorinfo`, and everything imports successfully and `listdescriptors` shows the correct descriptor as expected?\r\n\r\n> any idea how to check this? using another shell?\r\n\r\nUsing a script is good enough. It tells you that there's something wrong with your command or your shell.\r\n\r\n***\r\n\r\nLooking at this a bit more closely, I see now that the issue is that you've entered the command without escaping your `'`. You begin the entire imports argument with a `'`, so the internal `'` for the key origins are going to be interpreted by your shell as being the end of a string rather than a character to include in the string. You can even see this in how github renders those characters with different colors. You'll need to figure out how to escape them for your shell (typically `\\'` works), or just use `h`s.",
      "created_at" : "2023-08-27T15:43:29Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/28351#issuecomment-1694699418",
      "id" : 1694699418,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28351",
      "node_id" : "IC_kwDOABII585lAw-a",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1694699418/reactions"
      },
      "updated_at" : "2023-08-27T15:44:56Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1694699418",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/3782274?v=4",
         "events_url" : "https://api.github.com/users/achow101/events{/privacy}",
         "followers_url" : "https://api.github.com/users/achow101/followers",
         "following_url" : "https://api.github.com/users/achow101/following{/other_user}",
         "gists_url" : "https://api.github.com/users/achow101/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/achow101",
         "id" : 3782274,
         "login" : "achow101",
         "node_id" : "MDQ6VXNlcjM3ODIyNzQ=",
         "organizations_url" : "https://api.github.com/users/achow101/orgs",
         "received_events_url" : "https://api.github.com/users/achow101/received_events",
         "repos_url" : "https://api.github.com/users/achow101/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/achow101/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/achow101/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/achow101"
      }
   }
]
