{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "Fixes #26245. I'm doing it because it came to my mind after reviewing #28339.\r\n\r\nInside the `invalidateblock` process, we update the best_header by manually calling `InvalidChainFound` after disconnecting blocks.\r\n\r\nWe need to do the same for `reconsiderblock` and update the chain `best_header` field after finishing the process.\r\n\r\nNote: the only difference between this two commands is that `reconsiderblock` does not have its own separate function, it's a plain RPC command that resets the block index flag and calls `ActivateBestChain`.\r\n\r\nThe only place we forwardly update the best_header field is within `AddToBlockIndex` which is not called by `reconsiderblock` since the block is already in the block index. Thus why we need to manually update it after reconsidering a block.\r\n\r\nTesting Notes:\r\n- Comment the fix line and run the `rpc_invalidateblock.py` test.\r\n- Or, call `invalidateblock` and compare the `getblockchaininfo()` 'headers' num value against `getblockcount()`, then do the same after calling `reconsiderblock()`.",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29913/comments",
   "created_at" : "2024-04-19T12:19:48Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29913/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/29913",
   "id" : 2252837609,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29913/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585tKg8C",
   "number" : 29913,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/29913.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29913",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/29913.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/29913"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29913/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29913/timeline",
   "title" : "bugfix: update chainman best_header after block reconsideration",
   "updated_at" : "2024-04-19T13:02:07Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29913",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
      "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
      "followers_url" : "https://api.github.com/users/furszy/followers",
      "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
      "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/furszy",
      "id" : 5377650,
      "login" : "furszy",
      "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
      "organizations_url" : "https://api.github.com/users/furszy/orgs",
      "received_events_url" : "https://api.github.com/users/furszy/received_events",
      "repos_url" : "https://api.github.com/users/furszy/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/furszy"
   }
}
